### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by jasminnes** [niki9011/web-framework#1]
Вчера беше крайния срок за commit-ване. Ще ви помоля да ревъртнете промените от днес преди защитата утре.

**Comment by niki9011** [comment]
> Вчера беше крайния срок за commit-ване. Ще ви помоля да ревъртнете промените от днес преди защитата утре.

Върнах ги, извинявам се за което просто малко стилизация, незнаех, че има краен срок.

**Comment by niki9011** [comment]
Върнах ги, извинявам се за което просто малко стилизация, незнаех, че има
краен срок.
